name: flutter_lint_plus
description: Recommended lints for Flutter apps, packages, and plugins to encourage good coding practices.
version: 1.0.2
homepage: https://github.com/goodswifter/flutter_lint_plus.git

environment:
  sdk: '>=3.0.0'
  flutter: '>=3.0.0'

dependencies:
  # lints: ^2.0.0
